config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :professions, only: [:index, :show]
    end
  end

  scope module: :web do
    root to: "welcome#index"
    resources :articles, :professions, only: %i[index show]
    resources :reviews, only: %i[index]
    
    namespace :admin do
      root to: "admins#index"
      resource :profile, only: %i[edit update]
      resource :session, only: %i[new create destroy]
      resources :admins, :students, :courses, :teachers, :professions, :lessons do
        put 'restore'
        put 'del'
      end
      resources :articles do
        put 'publish'
        put 'unpublish'
      end
    end

    namespace :teacher do
      root to: "welcome#index"
      resource :profile, only: %i[edit update]
      resource :session, only: %i[new create destroy]
      resources :courses, only: %i[index new create show edit update] do
        scope module: :courses do
          resources :lessons, only: %i[new create]
        end
      end

      resources :lessons do
        put 'restore'
        put 'del'
      end

      resources :articles do
        put "publish"
        put "unpublish"
      end

      resources :student_homeworks do
        put 'check'
        put 'modify'
        put 'adopted'
      end
    end

    namespace :student do
      root to: 'welcome#index'
      resource :profile, only: %i[edit update show] do
        put "delete_photo"
      end
      resource :session, only: %i[new create destroy]
      resources :student_courses, only: %i[create destroy]
      resources :courses, only: %i[index show] do
        scope module: :courses do
          resources :lessons, only: %i[show]
        end
      end
      resources :student_homeworks, only: %i[index show edit update]
      #resources :reviews, only: %i[index new create show]
    end
  end
end

app/models/article.rb
class Article < ApplicationRecord
  extend Enumerize
  validates :title, :body, :state, presence: true

  belongs_to :author, polymorphic: true

  state_machine initial: :published do
    state :published
    state :unpublished

    event :unpublish do
      transition published: :unpublished
    end

    event :publish do
      transition unpublished: :published
    end
  end
end

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < Api::V1::ApplicationController
  def index
    articles = Article.active.order(title: :asc)
    render json: articles, each_serializer: ArticleIndexSerializer
  end

  def show
    article = Article.active.find(params[:id])
    render json: article, serializer: ArticleShowSerializer
  end
end

app/controllers/web/admin/articles_controller.rb
class Web::Admin::ArticlesController < Web::Admin::ApplicationController
  def index
    @search = Article.ransack(params[:q])
    @pagy, @articles = pagy(@search.result)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_attrs)
    @article.author = current_admin

    if @article.save
      redirect_to action: :index
    else
      render action: :new
    end
  end

  def show
    @article = Article.find(params[:id]).decorate
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_attrs)
      redirect_to action: :index
    else
      render action: :edit
    end
  end

  def unpublish
    article = Article.find(params[:article_id])
    article.unpublish!
    redirect_to action: :index
  end

  def publish
    article = Article.find(params[:article_id])
    article.publish!
    redirect_to action: :index
  end

  private

  def article_attrs
    params.require(:article).permit(:title, :body, :author)
  end
end

app/controllers/web/articles_controller.rb
class Web::ArticlesController < Web::ApplicationController
  def index
    @articles = Article.where(state: :published).decorate
  end

  def show
    @article = Article.find(params[:id]).decorate
  end
end

app/controllers/web/teacher/articles_controller.rb
class Web::Teacher::ArticlesController < Web::Teacher::ApplicationController
  def index
    @pagy, @articles = pagy(Article.decorate)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_attrs)
    @article.author = current_teacher

    if @article.save
      redirect_to action: :index
    else
      render action: :new
    end
  end

  def show
    @article = Article.find(params[:id]).decorate
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_attrs)
      redirect_to action: :index
    else
      render action: :edit
    end
  end

  def unpublish
    article = Article.find(params[:article_id])
    article.unpublish!
    redirect_to action: :index
  end

  def publish
    article = Article.find(params[:article_id])
    article.publish!
    redirect_to action: :index
  end

  private

  def article_attrs
    params.require(:article).permit(:title, :body, :author)
  end
end

app/views/web/admin/articles/edit.html.haml
= simple_form_for @article, url: admin_article_path(@article.id) do |f|
  = f.input :title
  = f.input :body
  = f.button :submit, t('.create_article'), class: 'btn btn-outline-secondary'
  = link_to t('.cancel'), admin_articles_path, class: 'btn btn-outline-secondary'

app/views/web/admin/articles/index.html.haml
%a.pull-right
  %h1= t('articles')
= search_form_for @search, url: admin_articles_path do |f|
  = f.label :title_cont
  = f.search_field :title_cont
  = f.button t('search_form.search_button'), class: 'btn btn-success btn'
%table.table.table-striped.table-hover
  %tr
    %th= Article.human_attribute_name(:id)
    %th= Article.human_attribute_name(:title)
    %th= Article.human_attribute_name(:author)
    %th= Article.human_attribute_name(:state)
    %th{:colspan => "2"}= t('.control')
  - @articles.each do |article|
    %tr
      %td= article.id
      %td= article.title
      %td= article.author.decorate.name
      %td= article.human_state_name
      %td= link_to t('.view profile'), admin_article_path(article.id), class: 'btn btn-success btn'
%td= link_to t('.add'), new_admin_article_path, class: 'btn btn-outline-secondary'
!= pagy_bootstrap_nav(@pagy)

app/views/web/admin/articles/new.html.haml
= simple_form_for @article, url: admin_articles_path do |article|
  = article.input :title
  = article.input :body
  = article.button :submit, t('.create_article'), class: 'btn btn-outline-secondary'
  = link_to t('.cancel'), admin_articles_path, class: 'btn btn-outline-secondary'

app/views/web/admin/articles/show.html.haml
%a.pull-right
  %h1= t('articles')
%table.table.table-hover
  %thead
    %tr
      %th= Article.human_attribute_name(:id)
      %th= Article.human_attribute_name(:title)
      %th= Article.human_attribute_name(:body)
      %th= Article.human_attribute_name(:author)
      %th= Article.human_attribute_name(:updated_at)
      %th= Article.human_attribute_name(:state)
      %th{:colspan => "2"}= t('.control')
  %tbody
    %tr
      %td= @article.id
      %td= @article.title
      %td= @article.body
      %td= @article.author.name
      %td= @article.updated_at
      %td= @article.human_state_name
      %td= link_to t('.edit'), edit_admin_article_path(@article.id), class: 'btn btn-success btn-sm'
      - @article.state_events.each do |event|
        %td= link_to human_state_event_name(:article, 'state', event), {:action => event.to_sym, :article_id => @article.id}, method: :put, data: { confirm: t('are you sure?')}, class: 'btn btn-danger btn-sm'
= link_to t('.back'), admin_articles_path, class: 'btn btn-outline-secondary'