config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :professions, only: [:index, :show]
    end
  end

  scope module: :web do
    root to: "welcome#index"
    resources :articles, :professions, only: %i[index show]
    resources :reviews, only: %i[index]
    
    namespace :admin do
      root to: "admins#index"
      resource :profile, only: %i[edit update]
      resource :session, only: %i[new create destroy]
      resources :admins, :students, :courses, :teachers, :professions, :lessons do
        put 'restore'
        put 'del'
      end
      resources :articles do
        put 'publish'
        put 'unpublish'
      end
    end

    namespace :teacher do
      root to: "welcome#index"
      resource :profile, only: %i[edit update]
      resource :session, only: %i[new create destroy]
      resources :courses, only: %i[index new create show edit update] do
        scope module: :courses do
          resources :lessons, only: %i[new create]
        end
      end

      resources :lessons do
        put 'restore'
        put 'del'
      end

      resources :articles do
        put "publish"
        put "unpublish"
      end

      resources :student_homeworks do
        put 'check'
        put 'modify'
        put 'adopted'
      end
    end

    namespace :student do
      root to: 'welcome#index'
      resource :profile, only: %i[edit update show] do
        put "delete_photo"
      end
      resource :session, only: %i[new create destroy]
      resources :student_courses, only: %i[create destroy]
      resources :courses, only: %i[index show] do
        scope module: :courses do
          resources :lessons, only: %i[show]
        end
      end
      resources :student_homeworks, only: %i[index show edit update]
      #resources :reviews, only: %i[index new create show]
    end
  end
end

app/views/layouts/admin/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .collapse.navbar-collapse
    .navbar-nav
      = link_to t('header.home'), admin_root_path, class: 'navbar-brand'
      = link_to t('header.admins'), admin_admins_path, class: 'nav-item nav-link'
      = link_to t('header.students'), admin_students_path, class: 'nav-item nav-link'
      = link_to t('header.teachers'), admin_teachers_path, class: 'nav-item nav-link'
      = link_to t('header.professions'), admin_professions_path, class: 'nav-item nav-link'
      = link_to t('header.courses'), admin_courses_path, class: 'nav-item nav-link'
      = link_to t('header.lessons'), admin_lessons_path, class: 'nav-item nav-link'
      = link_to t('header.articles'), admin_articles_path, class: 'nav-item nav-link'
      = link_to t('header.personal_account'), edit_admin_profile_path, class: 'nav-item nav-link'
      %ul.navbar-num
  %div
    %div{style: 'color: white'}= current_admin.email
    %div= link_to t('header.exit'), admin_session_path, method: :delete, class: 'btn btn-outline-secondary btn-sm'

app/views/layouts/admin/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title App
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'admin_application', media: 'all'
    = javascript_include_tag 'admin_application'
  %body
    .container
      - if admin_signed_in?
        = render 'layouts/admin/header'
      = yield