config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :professions, only: [:index, :show]
    end
  end

  scope module: :web do
    root to: "welcome#index"
    resources :articles, :professions, only: %i[index show]
    resources :reviews, only: %i[index]
    
    namespace :admin do
      root to: "admins#index"
      resource :profile, only: %i[edit update]
      resource :session, only: %i[new create destroy]
      resources :admins, :students, :courses, :teachers, :professions, :lessons do
        put 'restore'
        put 'del'
      end
      resources :articles do
        put 'publish'
        put 'unpublish'
      end
    end

    namespace :teacher do
      root to: "welcome#index"
      resource :profile, only: %i[edit update]
      resource :session, only: %i[new create destroy]
      resources :courses, only: %i[index new create show edit update] do
        scope module: :courses do
          resources :lessons, only: %i[new create]
        end
      end

      resources :lessons do
        put 'restore'
        put 'del'
      end

      resources :articles do
        put "publish"
        put "unpublish"
      end

      resources :student_homeworks do
        put 'check'
        put 'modify'
        put 'adopted'
      end
    end

    namespace :student do
      root to: 'welcome#index'
      resource :profile, only: %i[edit update show] do
        put "delete_photo"
      end
      resource :session, only: %i[new create destroy]
      resources :student_courses, only: %i[create destroy]
      resources :courses, only: %i[index show] do
        scope module: :courses do
          resources :lessons, only: %i[show]
        end
      end
      resources :student_homeworks, only: %i[index show edit update]
      #resources :reviews, only: %i[index new create show]
    end
  end
end

app/models/profession.rb
class Profession < ApplicationRecord
  include ProfessionRepository

  has_many :course_professions, dependent: :nullify
  has_many :courses, through: :course_professions

  validates :title, :description, :state, presence: true
  validates :title, length: { maximum: 50 }, uniqueness: true

  state_machine initial: :active do
    state :active
    state :deleted

    event :del do
      transition active: :deleted
    end

    event :restore do
      transition deleted: :active
    end
  end
end

app/controllers/api/v1/professions_controller.rb
class Api::V1::ProfessionsController < Api::V1::ApplicationController
  def index
    professions = Profession.active.order(title: :asc)
    render json: professions, each_serializer: ProfessionIndexSerializer
  end

  def show
    profession = Profession.active.find(params[:id])
    render json: profession, serializer: ProfessionShowSerializer
  end
end

app/controllers/web/admin/professions_controller.rb
class Web::Admin::ProfessionsController < Web::Admin::ApplicationController
  def index
    @search = Profession.ransack(params[:q])
    @pagy, @professions = pagy(@search.result)
  end

  def new
    @profession = Profession.new
    authorize @profession
  end

  def create
    @profession = Profession.new(profession_attrs)

    if @profession.save
      redirect_to action: :index
    else
      render action: :new
    end
  end

  def show
    @profession = Profession.find(params[:id]).decorate
  end

  def edit
    @profession = Profession.find(params[:id])
    authorize @profession
  end

  def update
    @profession = Profession.find(params[:id])

    if @profession.update(profession_attrs)
      redirect_to action: :show
    else
      render action: :edit
    end
  end

  def del
    profession = Profession.find(params[:profession_id])
    profession.del!
    redirect_to action: :index
  end

  def restore
    profession = Profession.find(params[:profession_id])
    profession.restore!
    redirect_to action: :index
  end

  private

  def profession_attrs
    params.require(:profession).permit(:title, :description, course_ids: [])
  end
end

app/controllers/web/professions_controller.rb
class Web::ProfessionsController < Web::ApplicationController
  def index
    @professions = Profession.active.decorate
  end

  def show
    @profession = Profession.find(params[:id]).decorate
  end
end

app/views/web/admin/professions/edit.html.haml
= simple_form_for @profession, url: admin_profession_path(@profession.id) do |profession|
  = profession.input :title
  = profession.input :description
  = profession.association :courses, as: :check_boxes
  = profession.button :submit, t('.create_profession'), class: 'btn btn-outline-secondary'
  = link_to t('.cancel'), admin_professions_path, class: 'btn btn-outline-secondary' 

app/views/web/admin/professions/index.html.haml
%a.pull-right
  %h1= t('professions')
= search_form_for @search, url: admin_professions_path do |f|
  = f.label :title_cont
  = f.search_field :title_cont
  = f.button t('search_form.search_button'), class: 'btn btn-success btn'
%table.table.table-striped.table-hover
  %tr
    %th= Profession.human_attribute_name(:id)
    %th= Profession.human_attribute_name(:title)
    %th= Profession.human_attribute_name(:description)
    %th= Profession.human_attribute_name(:state)
    %th{:colspan => "2"}= t('.control')
  - @professions.each do |profession|
    %tr
      %td= profession.id
      %td= profession.title
      %td= profession.description
      %td= profession.human_state_name
      %td= link_to t('.view profile'), admin_profession_path(profession), class: 'btn btn-success btn'
- if policy(@professions).new?
  %td= link_to t('.add'), new_admin_profession_path, class: 'btn btn-outline-secondary' 
!= pagy_bootstrap_nav(@pagy)

app/views/web/admin/professions/new.html.haml
= simple_form_for @profession, url: admin_professions_path do |profession|
  = profession.input :title
  = profession.input :description
  = profession.association :courses, as: :check_boxes
  = profession.button :submit, t('.create_profession'), class: 'btn btn-outline-secondary'
  = link_to t('.cancel'), admin_professions_path, class: 'btn btn-outline-secondary'

app/views/web/admin/professions/show.html.haml
%a.pull-right
  %h1= t('professions')
%table.table.table-striped.table-hover
  %thead
    %tr
      %th= Profession.human_attribute_name(:id)
      %th= Profession.human_attribute_name(:title)
      %th= Profession.human_attribute_name(:description)
      %th= Profession.human_attribute_name(:course)
      %th= Profession.human_attribute_name(:created_at)
      %th= Profession.human_attribute_name(:state)
      - if policy(@profession).edit?
        %th{:colspan => "2"}= t('.control')
  %tbody
    %tr
      %td= @profession.id
      %td= @profession.title
      %td= @profession.description
      %td= @profession.courses.map(&:title).join(', ')
      %td= @profession.created_at
      %td= @profession.human_state_name
      - if policy(@profession).edit?
        %td= link_to t('.edit'), edit_admin_profession_path(@profession.id), class: 'btn btn-success btn-sm'
        -if @profession.can_del?
          %td= link_to t('.del'), admin_profession_del_path(@profession.id), method: :put, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'
        -if @profession.can_restore?
          %td= link_to t('.restore'), admin_profession_restore_path(@profession.id), method: :put, data: { confirm: 'Are you sure?' }, class: 'btn btn-success btn-sm'
= link_to t('.back'), admin_professions_path, class: 'btn btn-outline-secondary' 